services:
  flutter:
    container_name: flutter
    build: ./frontend/
    command: bash -c "flutter clean && flutter build web && firebase emulators:start && flutter clean && flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8888" 
    tty: true
    env_file: .env
    volumes:
      - ./frontend/app:/app
    ports:
      - 4000:4000
      - 5000:5000
      - 9099:9099
      - 8000:8000
      - 8888:8888
    depends_on:
      - go

  go:
    container_name: go
    build: ./backend/
    volumes:
      - ./backend/app:/app/
      - tmp-data:/app/tmp
    ports:
      - 8080:8080
    env_file:
      - .env

  
volumes:
  tmp-data: