services:
  flutter:
    container_name: flutter
    build: ./frontend/
    command: bash -c "flutter clean && flutter build web && /bin/bash" 
    tty: true
    env_file: .env
    volumes:
      - ./frontend/app:/app
    ports:
      - 4000:4000
      - 5000:5000
      - 9099:9099
      - 8000:8000
    depends_on:
      - go

  go:
    container_name: go
    build: ./backend/
    volumes:
      - ./backend/:/app/
      - tmp-data:/app/tmp
    ports:
      - 8080:8080
    env_file:
      - .env

  
volumes:
  tmp-data: