name: Deploy to Firebase Hosting on PR
on: pull_request

permissions: write-all

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter のインストール clone がはやい
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      # PATH を通す
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      # パッケージのダウンロード
      - name: Download Flutter packages
        working-directory: ./frontend/app
        run: flutter pub get
      
      # ビルド
      - working-directory: ./frontend/app
        run: flutter build web
      
      - name: Enable flutter web
        run: flutter config --enable-web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: health-care-app-3e333
          entryPoint: ./frontend/app
          expires: 30d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks